dependencies:
  # - <organization/repo>@<version> Inform brownie from where to download the chainlink imports of the FundMe.sol
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler: 
  solc:
    remappings:
    # Whenever compiler sees @chainlink, we refer to it as the dependancy added above
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
wallets: 
  from_key: ${PRIVATE_KEY}

networks:
  goerli: 
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-development: 
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development: 
    verify: False
  ganache-local:
    verify: False
